In [123]:
import os
from pathlib import Path

import pandas as pd
import numpy as np

import pytest

from sklearn_pandas import DataFrameMapper

from sklearn.preprocessing import LabelBinarizer, StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix, log_loss, recall_score, accuracy_score
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline

In [124]:
import sklearn_pandas

In [125]:
datadir = Path(os.getcwd()) / 'data'
print(datadir)

C:\Users\Jasa\Desktop\risk\risk-ai-workshop-master\notebooks\data


## Model selection exercise: preprocessing and generalization error for hit rate

Difficulty: **

Train and select from among at least two classifiers for the hit-rate (fake) data in `notebooks/data/hits.csv` and estimate the selected model's generalization error.

In [126]:
import numpy as np

df = pd.read_csv(datadir / 'hits.csv')
print(df.head(7))

df = df.replace('financial', 0)
df = df.replace('property', 1)
df = df.replace('liability', 2)

matrix = np.array(df)
X = matrix[:,:3]
y = matrix[:,3]
print(X,y)




edge = len(y) // 3
X_train = X[0 : edge,:]
y_train = y[0 : edge]

X_validate = X[edge : 2 * edge,:]
y_validate = y[edge : 2 * edge]

X_test = X[2 * edge:, :]
y_test = y[2 * edge:]


  product_type  days  rating  hit
0     property     3       1    0
1    liability     1       0    0
2    financial     0       1    0
3    liability     3       0    0
4    liability     0       0    1
5     property     1       1    0
6     property     2       0    1
[[1 3 1]
 [2 1 0]
 [0 0 1]
 ...
 [1 3 0]
 [2 2 0]
 [0 0 1]] [0 0 0 ... 1 1 1]


In [127]:
#LogisticRegression method 
log_reg = LogisticRegression(random_state=0).fit(X_train, y_train)
log_reg
result_log_reg = log_reg.score(X_train, y_train)
print('Logistic Regression:{}'.format(result_log_reg))

#GradientBoostingClassifier

grad_boost_classifier = GradientBoostingClassifier().fit(X_train, y_train)
result_grad_boost = grad_boost_classifier.score(X_train, y_train)
print('Gradient Boosting Classifier:{}'.format(result_grad_boost))

Logistic Regression:0.7527839643652561
Gradient Boosting Classifier:0.7577951002227171


## Model selection exercise: A simple, high accuracy predictive model

Difficulty: *

Choose a simple model for the fake data `notebooks/data/lightning.csv` with at least 99% accuracy on the test set. The simpler the better. 

In [131]:
df = pd.read_csv(datadir / 'lightning.csv')
df.head()

city  year  lightning_strike
0         Ajdovščina  1990                 0
1             Sežana  1990                 0
2           Ljutomer  1990                 0
3  Slovenske Konjice  1990                 0
4         Radovljica  1990                 0

In [146]:
rate_of_strikes = df['lightning_strike'].mean()
print("Accuracy of model that always (for any city and year) return 0 is: {}%.".format(round(1- number_of_strikes,4)*100))



Accuracy of model that always (for any city and year) return 0 is: 99.87%.
